name: Build and Push Docker image

on:
  push:
    branches:
      - main  # You can change this to whatever branch you want

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ubermensch25/tojeck:latest

    - name: Image Digest
      run: echo "Docker image pushed to Docker Hub: ubermensch25/tojeck:latest"
