name: Build and Push Docker image

# Trigger this workflow on push to the main branch
on:
  push:
    branches:
      - main  # You can change this to any branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository containing your code
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Docker Buildx (a Docker CLI plugin that extends the Docker build command)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Log in to Docker Hub using the secrets stored in GitHub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}   # GitHub secret
          password: ${{ secrets.DOCKER_PASSWORD }}   # GitHub secret

      # Build and push Docker image to Docker Hub
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile  # Make sure the path to your Dockerfile is correct
          push: true
          tags: ubermensch25/tojeck:latest

      # Optional: Output message showing success
      - name: Image Digest
        run: echo "Docker image pushed to Docker Hub:ubermensch25/tojeck:latest"
